CREATE TABLE ACCOUNTS(
    ACCOUNT_NUMBER VARCHAR(10) PRIMARY KEY,

    BALANCE DECIMAL(19,2)
);

CREATE TABLE DEPOSIT_HISTORY(
	ACCOUNT_NUMBER VARCHAR(10),
	AMOUNT DECIMAL(19,2),
	DATE DATETIME DEFAULT(CURRENT_TIMESTAMP())
);

ALTER TABLE DEPOSIT_HISTORY ADD FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER);

INSERT INTO ACCOUNTS VALUES ('0000001',0.0);