CREATE DATABASE DEPOSIT
GO
USE DEPOSIT

CREATE TABLE ACCOUNTS(
    ACCOUNT_NUMBER VARCHAR(10) PRIMARY KEY,
    BALANCE DECIMAL(19,2)
)

CREATE TABLE DEPOSIT_HISTORY(
	ACCOUNT_NUMBER VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
	AMOUNT DECIMAL(2,2),
	DATE DATETIME DEFAULT(GETDATE())
)